### PR TITLE
fixed the markdown table

### PR DESCRIPTION
**Pull request by edgarcosta**
There were two spaces missing in the markdown tables on the top of the text.

### CODE REVIEW

**Comment by JohnCremona** [comment]
Any idea when this happened?  Thanks for fixing.  I cannot think of a good reason not to merge and see how it then looks, since I don't know any way of testing.

**Comment by edgarcosta** [comment]
I think it was when @AndrewVSutherland first introduced the tables...
Around June 13, e.g.: https://github.com/LMFDB/lmfdb-inventory/commit/82cf89fb901424760643f3f9269773f66bc39865

**Comment by JohnCremona** [comment]
Looks better now!  Thanks :)

**Comment by AndrewVSutherland** [comment]
@edgarcosta Thanks for fixing this, I'm not sure what happened (possibly I was using a bad markup viewer locally, I think I would have noticed this)

**Pull request merged**
