### PR TITLE
I added descriptions to the L-functions attributes

### PR DESCRIPTION
**Pull request by edgarcosta**

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
This PR converts the entire file from markup to html, is that really necessary/desirable?

**Comment by edgarcosta** [comment]
I added two new columns:
Description and Remarks.

I could stick with Markdown tables, but the text lines get quite long and really readable or easy to edit. If you feel that I should stick with a markdown table, I can easily convert the HTML table to a Markdown table.

**Comment by AndrewVSutherland** [comment]
HTML is fine, I just wanted to check that this was intentional and not inadvertent.

**Comment by edgarcosta** [comment]
Thanks!

**Pull request merged**
